name: "Hello Actions"
description: "Greet someone"
author: "octocat@github.com"

inputs: 
  MY_NAME:
      description: "Who to greet"
      required: true
      default: "World"

runs:
  using: "docker"
  image: "Docker file"


branding:
  icon: "mic"
  color: "purple"
